"""first

Revision ID: dc2281c33b10
Revises: 
Create Date: 2024-02-13 10:07:02.293017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2281c33b10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpu',
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.Column('us', sa.Float(), nullable=False),
    sa.Column('sy', sa.Float(), nullable=False),
    sa.Column('ni', sa.Float(), nullable=False),
    sa.Column('id', sa.Float(), nullable=False),
    sa.Column('wa', sa.Float(), nullable=False),
    sa.Column('hi', sa.Float(), nullable=False),
    sa.Column('si', sa.Float(), nullable=False),
    sa.Column('st', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dt')
    )
    op.create_table('mem',
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('free', sa.Float(), nullable=False),
    sa.Column('used', sa.Float(), nullable=False),
    sa.Column('cache', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dt')
    )
    op.create_table('process',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=False),
    sa.Column('mem', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=5), nullable=False),
    sa.Column('command', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('swap',
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('free', sa.Float(), nullable=False),
    sa.Column('used', sa.Float(), nullable=False),
    sa.Column('available', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('dt')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swap')
    op.drop_table('process')
    op.drop_table('mem')
    op.drop_table('cpu')
    # ### end Alembic commands ###
